library(foreign)
library(readxl)
library(dummies)
library(devtools)
library(broom)
library(readxl)
library(car)
library(het.test)

data <- read_excel("data.xlsx")
summary (data$edu)
data$edummy <- as.factor(data$edu)
data$edummy <- relevel(data$edummy, ref = '0')

lm1 <- lm(lgexp~ edummy, data = data) 
summary (lm1)
lm2 <- lm(lgexp~ edummy + lgincome, data = data) 
summary (lm2)
lm3 <- lm(lgexp~ edummy + lgincome + lgwealth, data = data) 
summary (lm3)
lm4 <- lm(lgexp~ edummy + lgincome + lgwealth + age, data = data) 
summary (lm4)
lm5 <- lm(lgexp~ edummy + lgincome + lgwealth + age + hukou, data = data) 
summary (lm5)
lm6 <- lm(lgexp~ edummy + lgincome + lgwealth + age + hukou + mar, data = data) 
summary (lm6)
lm7 <- lm(lgexp~ edummy + lgincome + lgwealth + age + hukou + mar + com, data = data) 
summary (lm7)
lm8 <- lm(lgexp~ edummy + lgincome + lgwealth + age + hukou + mar + com + gender, data = data) 
summary (lm8)


lm01 <- lm(engel~ edummy, data = data) 
summary (lm01)
lm02 <- lm(engel~ edummy + lgincome, data = data) 
summary (lm02)
lm03 <- lm(engel~ edummy + lgincome + lgwealth, data = data) 
summary (lm03)
lm04 <- lm(engel~ edummy + lgincome + lgwealth + age, data = data) 
summary (lm04)
lm05 <- lm(engel~ edummy + lgincome + lgwealth + age + hukou, data = data) 
summary (lm05)
lm06 <- lm(engel~ edummy + lgincome + lgwealth + age + hukou + mar, data = data) 
summary (lm06)
lm07 <- lm(engel~ edummy + lgincome + lgwealth + age + hukou + mar + com, data = data) 
summary (lm07)
lm08 <- lm(engel~ edummy + lgincome + lgwealth + age + hukou + mar + com + gender, data = data) 
summary (lm08)


par(mfrow=c(2,2)) 
plot(lm8)
par(mfrow=c(2,2)) 
plot(lm4)

vif(lm8)
bptest(lm8)
covmtx <- hccm(lm8)
coeftest(lm8, vcov = covmtx)

vif(lm4)
bptest(lm4)
covmtx <- hccm(lm4)
coeftest(lm4, vcov = covmtx)


